### ISSUE TITLE
图片加密建议

### ISSUE THREAD

**Issue by Steesha** [yuyumoko/LiteLoaderQQNT-Plugin-Eencode#12]
图片加密建议不要直接丢图床上面...推荐先通过key生成一个随机种子，这个随机种子再来加密图片，比如m*n的图片，对每一个像素进行遍历，将(i,j)与(rand() % m,rand() % n)进行交换（当然这样感觉强度也不是很大，但是足够）还可以考虑进行颜色变换，也是通过那个固定的随机种子，这样对于纯色图片来说也有很不错的加密效果，至于用户只需要提出issues就行，但是开发者就要考虑的很多了.....

**Comment by yuyumoko** [comment]
建议不错, 但是主要是来防藤子的
