### ISSUE TITLE
发送按钮歪的

### ISSUE THREAD

**Issue by Zhuazizizi** [yuyumoko/LiteLoaderQQNT-Plugin-Eencode#3]
我的加密发送按钮是歪的，没有用主题，印象中大概应该也没用什么插件对输入框布局改动，
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/107139732/379d33b4-b021-46ce-8668-9fdce5958a7e)

![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/107139732/d449e9fe-dcdc-4811-a4ea-8fcc617a0a1d)

**Comment by jy02534655** [comment]
我这里加密发送按钮都看不到，是不是zindex设置小了
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/4277777/1e6d1d11-5f7e-40bc-a8e9-dfa7458ec3b1)
还有设置里面模式下拉项也不能选
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/4277777/38d2631d-268a-4620-805a-9f77c539f55c)

![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/4277777/4307a001-d458-4653-8eb6-59f6b96bc4f3)

**Comment by MisakaSophia** [comment]
你们的按钮还在吗,我这看不到按钮.

**Comment by Zhuazizizi** [comment]
> > 我的加密发送按钮是歪的，没有用主题，印象中大概应该也没用什么插件对输入框布局改动， ![image](https://private-user-images.githubusercontent.com/107139732/318250221-379d33b4-b021-46ce-8668-9fdce5958a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Nzk2NzIsIm5iZiI6MTcxNDk3OTM3MiwicGF0aCI6Ii8xMDcxMzk3MzIvMzE4MjUwMjIxLTM3OWQzM2I0LWIwMjEtNDZjZS04NjY4LTlmZGNlNTk1OGE3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNzA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzkzM2NhMWVmMzc3YjNjZDMwODYwYTU0YzlmNGQwYTQ0NGQ5NmI2NDdmZGFlZTg5MmJjYzkxZWY0MmNkYzBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sxI61nWe8l88Dep2NMVCFkYQk6jKKJHlJ16ZD1LSfdA)
> > ![image](https://private-user-images.githubusercontent.com/107139732/318248276-d449e9fe-dcdc-4811-a4ea-8fcc617a0a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Nzk2NzIsIm5iZiI6MTcxNDk3OTM3MiwicGF0aCI6Ii8xMDcxMzk3MzIvMzE4MjQ4Mjc2LWQ0NDllOWZlLWRjZGMtNDgxMS1hNGVhLThmY2M2MTdhMGExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNzA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNThiMWI4YTE3Y2M1YTdhNTJlNzVkZDJmZGZhZGFkNjU1OTYyZGI1Mzc5YzZlNThiMjdmNWNiNTAwMzE3ZDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.As3Aqbbpm2G7LM6ABZACn0RIysPoh4joV449uhgKvys)
> 
> 我的情况也一样，有解决办法么

也许是更新qq把，本来我是凑活用，现在升了9.9.9-23361后一切正常了。

**Comment by 200433zc** [comment]
目前
![Uploading CopyQ.TrSgMU.png…]()
windows端的在单插件下仍然无法显示加密发送按钮
![CopyQ YeZqFH](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/62494140/8b8aa40d-8b9f-43d3-b10c-6e9bca047026)

**Comment by Zhuazizizi** [comment]
> 目前
> ![Uploading CopyQ.TrSgMU.png…]()
> windows端的在单插件下仍然无法显示加密发送按钮
> ![CopyQ YeZqFH](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/62494140/8b8aa40d-8b9f-43d3-b10c-6e9bca047026)
> 

我也不知道到底啥原因我更新完qq就正常了，不行可以试试仿tg类主题插件，我在那个布局下发送按钮也会出现

**Comment by 200433zc** [comment]
> > 目前
> > ![Uploading CopyQ.TrSgMU.png…]()
> > windows端的在单插件下仍然无法显示加密发送按钮
> > ![CopyQ YeZqFH](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/62494140/8b8aa40d-8b9f-43d3-b10c-6e9bca047026)
> > 
> 
> 我也不知道到底啥原因我更新完qq就正常了，不行可以试试仿tg类主题插件，我在那个布局下发送按钮也会出现

试了下还是不行，谢谢了，等修复（）

**Comment by MisakaSophia** [comment]
![QQ截图20240510202119](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/125279361/a66eecee-8780-4cff-9847-46c3700f5afc)
![QQ截图20240510202153](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/125279361/71d5ae33-5d5d-4932-92ea-ee34e3f17bb9)
![QQ截图20240510202213](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/125279361/ccd892a9-874b-4f99-a180-2bf0324c373d)
还是不行,刚试了那tg皮肤也不行

**Comment by aknyzsd** [comment]
> 我这里加密发送按钮都看不到，是不是zindex设置小了 ![image](https://private-user-images.githubusercontent.com/4277777/318385131-1e6d1d11-5f7e-40bc-a8e9-dfa7458ec3b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzUxODIsIm5iZiI6MTcxNjQ3NDg4MiwicGF0aCI6Ii80Mjc3Nzc3LzMxODM4NTEzMS0xZTZkMWQxMS01ZjdlLTQwYmMtYThlOS1kZmE3NDU4ZWMzYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTQzNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEyOTk3MTU1NjgzYWEzOWVhMzdkYTlmMzU0OGI5NGM2MjMyNDdjNmIwOGExOTc4YWUzYjE5NmU4YzcxM2Y4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m2aZVjc0_RqzpAiYgKqfRywn7iZxKuRWaThVAc5zegw) 还有设置里面模式下拉项也不能选 ![image](https://private-user-images.githubusercontent.com/4277777/318385306-38d2631d-268a-4620-805a-9f77c539f55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzUxODIsIm5iZiI6MTcxNjQ3NDg4MiwicGF0aCI6Ii80Mjc3Nzc3LzMxODM4NTMwNi0zOGQyNjMxZC0yNjhhLTQ2MjAtODA1YS05Zjc3YzUzOWY1NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTQzNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlYzVmNDdmZTJmNjc3ODQ1M2QwZmNkNDQxYjQ5ZDhlOWRlY2NkZTQ0YjQ2MzhkYmM0YzI3YTNiMGU3NDk3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J6ztoPxdbTlOFsNBnvr6SqmRj3Ezvfay6N4gPiznpdQ)
> 
> ![image](https://private-user-images.githubusercontent.com/4277777/318384978-4307a001-d458-4653-8eb6-59f6b96bc4f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzUxODIsIm5iZiI6MTcxNjQ3NDg4MiwicGF0aCI6Ii80Mjc3Nzc3LzMxODM4NDk3OC00MzA3YTAwMS1kNDU4LTQ2NTMtOGViNi01OWY2Yjk2YmM0ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTQzNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdmNDkyYzg1ZDQzMGY3NjVhZjFmZjJlNTI5MzU0ODdkYWYxOWE4NDlhZTliYWRiOTllZTI5Njk1MTVlMTFjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8XlASqdmIDKeTMv0KdAzE9dz06REZbQW3vI7eRXUjME)

遇到同上问题求修复qwq
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/121467598/e77dc964-be25-4e6f-b171-42c0abfbcf29)
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/121467598/7b0aa463-c2c6-420e-ac24-6abb2d3486f2)
![image](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/121467598/bbf0ab14-11f5-4a8e-94a5-7fadfa8c2744)
