### ISSUE TITLE
在安装了Euphony的情况下会报错

### ISSUE THREAD

**Issue by XieLongWu** [yuyumoko/LiteLoaderQQNT-Plugin-Eencode#9]
猜测是否是内置的Euphony与Euphony原版（最新版）不同，且没有关闭调用外置的Euphony导致的冲突
![QQ_gkPUPQB5cY](https://github.com/user-attachments/assets/3c428119-a5c4-477f-bbed-9a6222bd0fb8)

**Comment by blblkang** [comment]
同样遇到了这个问题

**Comment by XieLongWu** [comment]
已修复
